version: '3.5'

services:
  api:
    build: .
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  db:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - .:/app
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres_data: