version: '1.1'

services:
  api:
    build: .
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - .:/app
    depends_on:
      - db
    command: python3 app.py

  db:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - .:/app
    ports:
      - 5433:5432
    environment:
      DATABASE_NAME: quiz_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
volumes:
  postgres_data: